# render.yaml for BloodConnect
services:
  # Backend: Node runtime
  - type: web
    name: bloodconnect-api
    runtime: node
    rootDir: ./backend
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        value: mongodb+srv://<username>:<password>@<cluster>.mongodb.net/bloodconnect?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "90d"
      - key: JWT_COOKIE_EXPIRES
        value: "90"
      - key: CLIENT_URL
        value: https://bloodconnect-web.onrender.com
      - key: CORS_ORIGIN
        value: https://bloodconnect-web.onrender.com
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: "BloodConnect <noreply@bloodconnect.com>"
    healthCheckPath: /api/health
    plan: free
    autoDeploy: true

  # Frontend: Static site (Vite)
  - type: web
    name: bloodconnect-web
    runtime: static
    rootDir: ./frontend
    buildCommand: 'npm install && npm run build'
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BASE_URL
        value: /api
      - key: VITE_API_URL
        value: https://bloodconnect-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    healthCheckPath: /
    plan: free
    autoDeploy: true