# Render Blueprint for BloodConnect Application
# Use dockerfile: at service level (no build: block)
services:
  # Frontend Service
  - type: web
    name: bloodconnect-web
    env: node
    dockerfile: ./frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BASE_URL
        value: /api
      - key: VITE_API_URL
        value: https://bloodconnect-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    healthCheckPath: /
    plan: free
    autoDeploy: true

  # Backend Service
  - type: web
    name: bloodconnect-api
    env: node
    dockerfile: ./backend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"

      - key: MONGODB_URI
        sync: false

      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: JWT_COOKIE_EXPIRES
        value: "90"

      - key: CLIENT_URL
        value: https://bloodconnect-web.onrender.com
      - key: CORS_ORIGIN
        value: https://bloodconnect-web.onrender.com

      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: "BloodConnect <noreply@bloodconnect.com>"

    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
