databases:
  - name: bloodconnect-mongo
    databaseName: bloodconnect
    plan: free
    ipAllowList: []  # Only Render services can access

services:
  # Backend Service
  - type: web
    name: bloodconnect-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        fromDatabase:
          name: bloodconnect-mongo
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "90d"
      - key: CLIENT_URL
        value: https://bloodconnect-web.onrender.com
      - key: CORS_ORIGIN
        value: https://bloodconnect-web.onrender.com
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: "BloodConnect <noreply@bloodconnect.com>"

  # Frontend Service (Static Site)
  - type: web
    name: bloodconnect-web
    runtime: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BASE_URL
        value: /api
      - key: VITE_API_URL
        value: https://bloodconnect-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html