# render.yaml for BloodConnect (Free Tier Configuration)
services:
  # Frontend: Static site (Vite) - Free tier
  - type: web
    name: bloodconnect-web
    env: node
    rootDir: ./frontend
    buildCommand: 'npm install && npm run build'
    staticPublishPath: ./dist
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BASE_URL
        value: /api
      - key: VITE_API_URL
        value: https://bloodconnect-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
    autoDeploy: true

  # Backend: Web service with free tier
  - type: web
    name: bloodconnect-api
    env: node
    rootDir: ./backend
    buildCommand: 'npm install'
    startCommand: 'node server.js'
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"
      - key: MONGODB_URI
        value: mongodb+srv://<username>:<password>@<cluster>.mongodb.net/bloodconnect?retryWrites=true&w=majority
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: "90d"
      - key: JWT_COOKIE_EXPIRES
        value: "90"
      - key: CLIENT_URL
        value: https://bloodconnect-web.onrender.com
      - key: CORS_ORIGIN
        value: https://bloodconnect-web.onrender.com
    plan: free
    autoDeploy: true