# Render Blueprint for BloodConnect
# Deploys a managed MongoDB instance, a Node/Express backend, and a Vite frontend

services:
  # Backend Service
  - type: web
    name: bloodconnect-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    dockerContext: ./backend
    autoDeploy: true
    envVars:
      # Server Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8000"
      
      # MongoDB Configuration
      - key: MONGO_URL
        sync: false
        value: ""
      
      # JWT Configuration
      - key: JWT_SECRET
        sync: false
        value: ""
      - key: JWT_EXPIRES_IN
        value: "90d"
      
      # AWS S3 Configuration
      - key: AWS_ACCESS_KEY
        sync: false
        value: ""
      - key: AWS_SECRET_KEY
        sync: false
        value: ""
      - key: AWS_REGION
        value: "ap-south-1"
      - key: S3_BUCKET_NAME
        value: "blood-connect-profile-pics"
      
      # Twilio Configuration
      - key: TWILIO_ACCOUNT_SID
        sync: false
        value: ""
      - key: TWILIO_AUTH_TOKEN
        sync: false
        value: ""
      - key: TWILIO_PHONE_NUMBER
        sync: false
        value: ""
      
      # CORS & Client Configuration
      - key: CLIENT_URL
        value: https://bloodconnect-web.onrender.com
      - key: CORS_ORIGIN
        value: https://bloodconnect-web.onrender.com

  # Frontend Service (Static Site)
  - type: web
    name: bloodconnect-web
    runtime: static
    rootDir: ./frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_BASE_URL
        value: /api
      - key: VITE_API_URL
        value: https://bloodconnect-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html