# Render Blueprint for BloodConnect Application
# Reference: https://render.com/docs/blueprint-spec
services:
  # Frontend Service
  - type: web
    name: bloodconnect-web
    env: node
    build:
      dockerfile: ./frontend/Dockerfile
    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_BASE_URL
        value: /api
      - key: VITE_API_URL
        value: https://bloodconnect-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    healthCheckPath: /
    plan: free
    autoDeploy: true

  # Backend Service
  - type: web
    name: bloodconnect-api
    env: node
    build:
      dockerfile: ./backend/Dockerfile
    envVars:
      # Server Configuration
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "10000"

      # MongoDB Configuration (set manually in Render dashboard / secrets)
      - key: MONGODB_URI
        sync: false

      # JWT Configuration
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 90d
      - key: JWT_COOKIE_EXPIRES
        value: "90"

      # CORS & Client URLs
      - key: CLIENT_URL
        value: https://bloodconnect-web.onrender.com
      - key: CORS_ORIGIN
        value: https://bloodconnect-web.onrender.com

      # Email Configuration (set manually)
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_FROM
        value: "BloodConnect <noreply@bloodconnect.com>"

    healthCheckPath: /api/health
    plan: free
    autoDeploy: true
